In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [8]:
df=pd.read_csv('/users/jenniferdersjant/Happiness-Team/data/covid_by_month.csv')

In [9]:
df.head(30)

,Country,month,year,New_cases,New_deaths,Cumulative_cases,Cumulative_deaths
0,Afghanistan,1,2020,0,0,0,0
1,Afghanistan,2,2020,5,0,0,0
2,Afghanistan,3,2020,161,4,5,0
3,Afghanistan,4,2020,1661,56,192,4
4,Afghanistan,5,2020,13353,194,2171,64
5,Afghanistan,6,2020,16265,485,15836,269
6,Afghanistan,7,2020,5183,536,31848,778
7,Afghanistan,8,2020,1620,131,36796,1287
8,Afghanistan,9,2020,1106,56,38282,1410
9,Afghanistan,10,2020,1980,71,39371,1462
10,Afghanistan,11,2020,4881,230,41425,1536
11,Afghanistan,12,2020,6115,426,46498,1774
12,Afghanistan,1,2021,2693,211,52513,2201
13,Afghanistan,2,2021,691,43,55059,2404
14,Afghanistan,3,2021,740,41,55733,2444
15,Afghanistan,4,2021,3291,141,56517,2489
16,Afghanistan,5,2021,12093,319,59939,2631
17,Afghanistan,6,2021,39754,1575,72977,2973
18,Albania,1,2020,0,0,0,0
19,Albania,2,2020,0,0,0,0
20,Albania,3,2020,205,12,0,0
21,Albania,4,2020,530,18,239,14
22,Albania,5,2020,363,2,735,30
23,Albania,6,2020,1437,30,1105,32
24,Albania,7,2020,2662,92,2580,65
25,Albania,8,2020,4183,126,5276,157
26,Albania,9,2020,4138,104,9513,284
27,Albania,10,2020,7116,118,13649,387
28,Albania,11,2020,16991,296,20875,509
29,Albania,12,2020,20102,376,38182,810